[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run serve"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacks]
node.version = "18"

[build.nixpacks.phases.build]
cmds = ["npm ci", "npm run build"]